### ISSUE TITLE
performance comparision 2.8.4-pX vs 3.0.0?

### ISSUE THREAD

**Issue by futtta** [tubalmartin/YUI-CSS-compressor-PHP-port#38]
Great to see you're pumping out updates like that @tubalmartin!

I see in the readme you state 3.0.0 is more performant, did you do benchmarks on this and if so can you share results?

**Comment by tubalmartin** [comment]
Hi @futtta ,

Maybe I created some confusion, sorry for that. In the v2.8.4-p10 changelog notes I lead users to read v3.0.0 changelog notes because I didn't want to repeat the same notes for both releases.

Performance should be pretty similar between v2.8.4-p10 & v3.0.0, that's what I meant since the code is the same regarding, fixes, improvements & performance optimizations made (v3 uses namespaces and two "static" helper classes but that's all the difference between the two).

Hope that answers your question ;)

**Comment by tubalmartin** [comment]
On a side note, apart from fixes and overall improvements, regarding performance we can say versions from v2.8.4-p10 onwards are more performant than previous ones.

**Comment by tubalmartin** [comment]
In fact I'm working on improving performance in some key areas so expect a new release in a few days :)

**Comment by futtta** [comment]
thanks for the feedback @tubalmartin, looking forward to the new release!

**Comment by tubalmartin** [comment]
v3.1.0 released! Top performance!

**Comment by futtta** [comment]
darn, going to have to look into that composer-stuff after all ;-)
